### ISSUE TITLE
External DNS resolution doesn't work with Openshift Origin 1.3.1

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-installer#89]
Since the upgrade to Openshift Origin 1.3.1, the DNS Servers defined within a docker container are

```
nameserver 172.30.0.1,
nameserver 10.0.2.3
```

and not 

```
nameserver 172.28.128.4,
nameserver 10.0.2.3
```

This behaviour could be explained how the dnsIP is defined within the node yaml config file created 

With 1.1.6

```
 more /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: 172.28.128.4
```

and 1.3.1

```
cat /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: ""
```
